openapi: "3.0.0"
info:
  title: employee insights
  description: employee insights
  version: 0.1.0
  contact:
    email: dev@focusorange.com
servers:
  - url: /api

paths:

  /companies/percentage_per_location/:
    get:
      operationId:
        getCompanyPercentagePerLocation
      parameters:
        - in: query
          name: percentageLimit
          schema:
            type: number
        - in: query
          name: locationId
          schema:
            type: integer
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: list
                items:
                  properties:
                    companyName:
                      type: string
                    percentage:
                      type: number

  /locations/:
    get:
      operationId:
        getLocations
      parameters:
        - in: query
          name: years
          schema:
            type: number
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: list
                items:
                  properties:
                    id:
                      type: integer
                    pathnames:
                      type: list
                      items:
                        type:
                          string
                    path:
                      type: list
                      items:
                        type:
                          integer